# Default config

SSH_PORT=22
DISABLE_ROOT_LOGIN=yes
DISABLE_PASSWORD_AUTH=no
ENABLE_UFW=yes
AUTO_UPDATES=yes
CONFIGURE_SSH=yes
DRY_RUN=no
ENABLE_FAIL2BAN=yes

FAIL2BAN_MAXRETRY=5
FAIL2BAN_FINDTIME=10m
FAIL2BAN_BANTIME=10m
